server:
  port: 8080
spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/mahsoly    change-log: classpath:db/changelog/master.changeset.xml
    user: postgres
    password: postgres
    drop-first: true
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver    url: jdbc:postgresql://localhost:5432/mahsoly
    username: postgres
    password: postgres
    name: mahsoly  
  jpa:
    hibernate:      ddl-auto: update
mahsoly:
  security:
    issuer-uri: http://localhost:8180/auth/realms/mahsoly